### ISSUE TITLE
AttributeError: 'RRi' object has no attribute 'shape'

### ISSUE THREAD

**Issue by mahmoodabed** [pss1207/sleep_apnea#2]
a01
  0%|                                                                                                                 | 0/488 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "pre_proc.py", line 95, in <module>
    if rri_filt.shape[0] > 5 and (np.min(rri_filt) >= MIN_RRI and np.max(rri_filt) <= MAX_RRI):
AttributeError: 'RRi' object has no attribute 'shape'

**Comment by Carlo-Carandang** [comment]
The shape attribute is from the numpy library function...did you import numpy? In pre_proc.py, it loads the numpy library as:
`import numpy as np`

**Comment by mahmoodabed** [comment]
> The shape attribute is from the numpy library function...did you import numpy? In pre_proc.py, it loads the numpy library as:
> `import numpy as np`

of course I imported numpy as np, also I downgraded keras as written.

**Comment by Carlo-Carandang** [comment]
Don't be rude...it works on my laptop.

**Comment by Carlo-Carandang** [comment]
And another thing @mahmoodabed , when someone answers you on these help forums, you first say "thank you" as a polite gesture for us sharing this repo with you. Responding "of course I..." is just very rude. I have no idea if you are new to coding or an expert.

**Comment by mahmoodabed** [comment]
@Carlo-Carandang sorry for being rude and thank you for your efforts. I am trying to create these two files **train_input.npy**  and **train_label.npy**  by using pre_proc.py . Did you use the given **npy**  files in the repository?

**Comment by pss1207** [comment]
> @Carlo-Carandang sorry for being rude and thank you for your efforts. I am trying to create these two files **train_input.npy** and **train_label.npy** by using pre_proc.py . Did you use the given **npy** files in the repository?

Hi, did you install hrv package?
This is the link of hrv package.
https://github.com/rhenanbartels/hrv

**Comment by mahmoodabed** [comment]
> > @Carlo-Carandang sorry for being rude and thank you for your efforts. I am trying to create these two files **train_input.npy** and **train_label.npy** by using pre_proc.py . Did you use the given **npy** files in the repository?
> 
> Hi, did you install hrv package?
> This is the link of hrv package.
> https://github.com/rhenanbartels/hrv

Sorry for the late reply and thank you.. Yes sir it is installed and the same problem

**Comment by mahmoodabed** [comment]
> Hi, did you install hrv package?
> This is the link of hrv package.
> https://github.com/rhenanbartels/hrv

could you please check the issue?

**Comment by Carlo-Carandang** [comment]
On https://physionet.org/tutorials/hrv-toolkit/ here are the instuctions:
Downloading and Installing the HRV Toolkit
1) On Windows, install the free Cygwin software first; see our tutorial for details. Cygwin includes the gcc C compiler and all other utilities needed to build and run the components of the HRV Toolkit on Windows. Start a Cygwin (terminal emulator) window and use it for all of the remaining steps.
2) Install the free WFDB and plt software packages.
3) The HRV toolkit is available as a tarball of sources (for all platforms) or as tarballs of prebuilt binaries for GNU/Linux (x86), Mac OS X (x86), Solaris (SPARC), or Windows/Cygwin. Download the version of your choice.
4) Unpack the HRV toolkit tarball you downloaded. (See the PhysioNet FAQ for information on unpacking tarballs.)
5) If you downloaded the sources, enter the source directory (HRV.src) and compile and install the toolkit by typing:
`make install`
If you downloaded the binaries, move the contents of the HRV directory into some directory in your PATH (or add the HRV directory to your PATH). The binaries require the same additional packages as the source distribution (WFDB, plt, and (on Windows) Cygwin).

**Comment by mahmoodabed** [comment]
> On https://physionet.org/tutorials/hrv-toolkit/ here are the instuctions:
> Downloading and Installing the HRV Toolkit
> 
>     1. On Windows, install the free Cygwin software first; see our tutorial for details. Cygwin includes the gcc C compiler and all other utilities needed to build and run the components of the HRV Toolkit on Windows. Start a Cygwin (terminal emulator) window and use it for all of the remaining steps.
> 
>     2. Install the free WFDB and plt software packages.
> 
>     3. The HRV toolkit is available as a tarball of sources (for all platforms) or as tarballs of prebuilt binaries for GNU/Linux (x86), Mac OS X (x86), Solaris (SPARC), or Windows/Cygwin. Download the version of your choice.
> 
>     4. Unpack the HRV toolkit tarball you downloaded. (See the PhysioNet FAQ for information on unpacking tarballs.)
> 
>     5. If you downloaded the sources, enter the source directory (HRV.src) and compile and install the toolkit by typing:
>        `make install`
>        If you downloaded the binaries, move the contents of the HRV directory into some directory in your PATH (or add the HRV directory to your PATH). The binaries require the same additional packages as the source distribution (WFDB, plt, and (on Windows) Cygwin).

Thanks you sir for your reply. I have tried and I have installed hrv without any change the same issue still appear. could you please share the versions of hrv, numpy, scipy and wfdb that you are using.

**Comment by Carlo-Carandang** [comment]
>I am trying to create these two files **train_input.npy** and **train_label.npy** by using pre_proc.py . Did you use the given **npy** files in the repository?

No- if you read the code pre_proc.py, those 2 npy files are written as the output of the pre_proc.py. The input to the pre_proc.py code is on line 34:

`data_path = '/Users/carandangc/Desktop/Sleep_Studies/data/www.physionet.org/physiobank/database/apnea-ecg/'`

This is the path where you downloaded the data from the following as described in the readme:
`wget -r -np http://www.physionet.org/physiobank/database/apnea-ecg/`

You most likely didn't change the data path on line 34 of pre_proc.py, and that's why you are getting the error: AttributeError: 'RRi' object has no attribute 'shape'. The RRi object has no attribute 'shape' as the object is empty. Change line 34 to your own data path for the downloaded data.

**Comment by mahmoodabed** [comment]
> No- if you read the code pre_proc.py, those 2 npy files are written as the output of the pre_proc.py. The input to the pre_proc.py code is on line 34:
> 
> `data_path = '/Users/carandangc/Desktop/Sleep_Studies/data/www.physionet.org/physiobank/database/apnea-ecg/'`
> 
> This is the path where you downloaded the data from the following as described in the readme:
> `wget -r -np http://www.physionet.org/physiobank/database/apnea-ecg/`
> 
> You most likely didn't change the data path on line 34 of pre_proc.py, and that's why you are getting the error: AttributeError: 'RRi' object has no attribute 'shape'. The RRi object has no attribute 'shape' as the object is empty. Change line 34 to your own data path for the downloaded data.

I couldn't fix this issue till now I am gonna close this issue thank you sir.
