### ISSUE TITLE
I need refrence papers for this project.

### ISSUE THREAD

**Issue by raushanraj24898** [pss1207/sleep_apnea#4]

**Comment by JoaaoPedroSantos** [comment]
I too

**Comment by pss1207** [comment]
Hi, There's no reference. I developed this algorithm based on my experience.

**Comment by JoaaoPedroSantos** [comment]
Okay. But can you give us a pre processing manual more detailed ? I'm a
beginner and i didn't understated why you extracted this features. Thanks.

**Comment by pss1207** [comment]
@Pedrosssantos You can just google it. "Heart Rate Variability", "RR Interval".
